- name: My first playbook to run on the localhost
  hosts: all
  connection: local
    # gather_facts: false
  
  # Example of map
  vars:
    show_message: false
    custom_message: I like Pokemon
  
  tasks:
    - name: My debug task
      debug:
        msg: |
            The custom_message value is: {{ custom_message }}
            {% if show_message %}
            hey!
            {% endif %}
